### ISSUE TITLE
Embedded images missing from sent messages, Dada Pro 9.0.2 Stable

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#534] opened 2016-01-09 18:08 UTC
If I use Mass Mailing > Send a Message to send an HTML message with an embedded image (inserted inline using TinyMCE and Core5 Filemanager) the message arrives with a broken link instead of the image. 

If I try to use Mass Mailing > Send a Webpage instead to do the same thing, the program hangs indefinitely with a "waiting" message when I try to send a test message.

In both cases, the problem seems to be solved by using the Source view in the editor to manually change the image link from a relative one to an absolute one. The problem is NOT solved by selecting "Change Image URLs to Absolute" in the Advanced options at the bottom of the HTML version tab (so possibly this is two bugs, I'm not sure).

**Comment by justingit** [comment] 2016-01-10 19:01
Yeah, found this too. I'm gonna mark this as a dupe of #533 and close it.

**Closed by justingit** 2016-01-10 19:01 UTC
