### ISSUE TITLE
No Confirmations sent in 11_0_5

### ISSUE THREAD

**Issue by AnthropAdmin** [justingit/dada-mail#746] opened 2018-07-16 01:02 UTC
Just installed 11_0_5 without ANY issues whatsoever.

Configured reCAPTCHA, bounce, etc. and made a test list.

Sent out a test invite and signed up another test on list signup page. Both invites are stuck in the Unconfirmed Subscribers because they never received their confirmation emails.

I resent both invites their Confirmation Email, but alas they still NEVER receive them. 

Both invites are able to receive and reply to the list owner's email configured in the list.

Thanks in advance for your assistance!

**Comment by justingit** [comment] 2018-07-16 02:11
Testing test, invites seem to be receiving (for me). Is there anything in the error log that would point to a different problem?  Is mailing using the app working at all?

![you_ve_been_invited_to_subscribe_to___new_list_name__-_dadamailtest_gmail_com_-_gmail](https://user-images.githubusercontent.com/39739/42740973-2d68ad34-886b-11e8-8d86-e2872d2cf54b.jpg)

**Comment by AnthropAdmin** [comment] 2018-07-16 13:49
Okay so I need to tell you that after the initial installation I re-ran the configuration using the global per your docs, because the installation video skipped the reCAPTCHA setup. Looked like everything worked just fine doing that.

However, here's the error log that you requested. I can't make any sense of it, of course. 

[errors-1531748893.txt](https://github.com/justingit/dada-mail/files/2197884/errors-1531748893.txt)

**Comment by AnthropAdmin** [comment] 2018-07-16 13:56
And yes the initial invite emails are going out.

![image](https://user-images.githubusercontent.com/41274487/42762454-6e5a6472-88de-11e8-93df-d56448737654.png)

**Comment by justingit** [comment] 2018-07-16 15:30
I'm not going through an error log, as this is not a support forum - this is a tracker to submit bugs to. 

So, 

Sent out a test invite and signed up another test on list signup page. Both invites are stuck in the Unconfirmed Subscribers because they never received their confirmation emails.

**Comment by justingit** [comment] 2018-07-17 19:20
Will close this issue soon, if there's no additional feedback - what the issue is doesn't seem clear,

**Comment by AnthropAdmin** [comment] 2018-07-19 22:22
I was simply reporting what I believed to be a bug. I sent you the error log because I thought you wanted it.

 

I’m not asking for tech support…

 

I have uninstalled Dada for now and will attempt another install to verify that the same problem exists if it indeed reproduces.

**Comment by justingit** [comment] 2018-07-19 23:29
Closing for lack of data of any issue.

**Closed by justingit** 2018-07-19 23:29 UTC
