### ISSUE TITLE
Bridge won't accept emails from subscribers

### ISSUE THREAD

**Issue by TeamVeritas** [justingit/dada-mail#629] opened 2017-01-08 23:40 UTC
It will accept emails from authorized_senders, but subscribers cannot send to the list.
The list is configured as a discussion list with pop3 account, moderation is turned off.

I first stumbled across this with 10.3.0 yesterday with a new list on a new domain.
I removed the database and all dada files, and reinstalled 10.2.4, then 10.2.2
I have a 10.2.1 installation on another domain which I tested just now, it is having the same issue - a subscriber can't post to the list even though it's set as discussion with no moderation.

Below is the results from the "Manually Check and Send"  The sender address IS subscribed to the list.

Mailing List: Test (test)
	* Logging into POP3 server 'mail.gordonsvilleairport.org'
	* POP3 Login succeeded.
	* Message count: 1

Message Size: 5431
	 Message is below maximum size allowed.
	 Message is below maximum soft size allowed.
	* Message Size is below both Soft and Hard Max Sizes.

* Checking Recipient: paul_iphone@ariesinternet.com
	* From List Owner: No.
	* Moderation disabled.
	* Discussion List Support is enabled.
		* From Subscriber: No.
	* Authorized Senders is enabled.
		* From Authorized Sender: No.
	* SpamAssassin check is disabled.

	Message did not pass verification.
	Reasons:
		* Message is not from a Subscriber
		* Message is not from the List Owner

	 Sending out, 'Not Allowed to Post' message to poster
	 Sending out, 'Not a Subscriber' message to List Owner
	* Removing message from server...
	* Disconnecting from POP3 server

Processing Digests:
------------------------------------------------------------------------
Mailing List: Test (test)
	* Digests are not enabled for, test

**Comment by TeamVeritas** [comment] 2017-01-08 23:48
I should add, both domains are running on a WHM/Cpanel VPS, using mysql backend.
I have a 6.0.2 list on another domain on the same server, I checked just now and it works fine - a subscriber can post to the list just fine.  Same email as is failing on the 10.x installations. 

List: Unity of Temple Choir(choir)
	Logging into POP3 server: mail.unityoftemple.org
	POP3 Login succeeded.

	Message count: 1
	* Message Size: 5381
	* Message is from: 'paul_iphone@ariesinternet.com'
	* From address is NOT from list owner address
	* Moderation disabled...
	* Discussion List Support enabled...
	* Message *is* from a current subscriber.
	* Authorized Senders List enabled...
	* Message is NOT from an Authorized Sender!
	* SpamAssassin check disabled...

**Comment by justingit** [comment] 2017-01-09 03:18
I believe this is a dupe of issue #628, which has a commit there to fix the issue. I'll release a new version (v10.3.1) that will also include this bugfix.

**Comment by TeamVeritas** [comment] 2017-01-09 03:35
Ah, good. Yes, the reCaptcha was enabled.
I had it tracked down to Validate.pm not returning anything on the subscription_check call...

**Comment by TeamVeritas** [comment] 2017-01-10 17:44
I added the patch from #628 and confirmed it worked.

**Comment by justingit** [comment] 2017-01-10 18:15
I'm going to close this, just as it seems to be a dupe pf #628 :)

**Closed** 2017-01-10 18:16 UTC
