### ISSUE TITLE
Error message disappearing

### ISSUE THREAD

**Issue by inet-dsps** [justingit/dada-mail#915] opened 2020-04-15 00:58 UTC
Hi,

My subscription works fine however please advice when same email is used for subscription out shows:

 (Mailing list information, including how to remove yourself, is located at the end of this message.)

Instead it does not show error message, please advice where on dadamail do we add error message?
This is Dada Mail version 10.3.6 Stable 02/06/17 

Im using modal for subscription appearance widget.

**Comment by justingit** [comment] 2020-04-15 17:15
I'm not sure if I understand the question you are asking. Is this a bug issue you're reporting?

**Comment by inet-dsps** [comment] 2020-04-15 20:50
Hi justin, not sure if it's a bug or what did you test the link I provided?

When you enter same email address twice for subscription an error should show to resend etc. Which in my case shows blank screen please check and advice feel free to subscribe.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by justingit** [comment] 2020-04-15 21:41
There's no link in the saved issue that I can see at: 

https://github.com/justingit/dada-mail/issues/915

If you're worried that there's a bug, you may want to first try upgrading, as you're running  a version of Dada Mail that's over three years old. I won't be able to provide a fix for such an old version. 

Cheers,

**Comment by inet-dsps** [comment] 2020-04-15 23:36
I have attached it as well.  Can you please confirm if my subscription form looks ok.

For some reasons unsubscribe does not work as well.

Regards,
Abdul.

**Comment by justingit** [comment] 2020-04-15 23:47
Please visit the issue in your browser: 

https://github.com/justingit/dada-mail/issues/915

As it looks like the info you want to add to the issue is being stripped when you're submitting it via email. 

**You may always want to first upgrade, to see if this issue is in the most recent version of Dada Mail, as I am not going to accept issues from a version that is so old.**

**Comment by inet-dsps** [comment] 2020-04-16 00:11
Hi please advice steps to upgrade? also can you confirm is unsubscribe option not supported on dadamail list?  

this is the code i used on my form:

    <p>     Subscribe 	    	    <input type="radio" name="f" id="f_s" value="subscribe" checked="checked" /></p>
    <p> Unsubscribe  	    <input type="radio" name="f" id="f_u" value="unsubscribe" /></p>

**Comment by inet-dsps** [comment] 2020-04-21 04:09
Hi Justin,

Just a last issue.
Im planning to upgrade this but in the meantime I need to know why my unsubscribe link appears before the content ?

This is my template:


                <br> <br>            <br> <br>
Click here to unsubscribe:            



Am I missing something?

Thanks.

**Comment by justingit** [comment] 2020-04-21 04:19
https://dadamailproject.com/d/FAQ-general.pod.html#Unsubscription-links-are-placed-on-top-of-my-mailing-list-messages-why

**Comment by inet-dsps** [comment] 2020-04-22 02:31
Thanks it dint helped.
Instead I switched back to private mode .  under mailing list > option (which will not show this option)

Since the mail content comes through bridge email. Meaning through my custom application mail sending, Will adding the below code on the footer of my application make it work:
<a href=””> Click here to unsubscribe </a>

Please confirm?

Thanks.

**Comment by justingit** [comment] 2020-04-22 05:04
It should. Please upgrade. I'm closing this, as this isn't an issue you're reporting.

**Closed by justingit** 2020-04-22 05:04 UTC
