### ISSUE TITLE
RFC6331: Moving DIGEST-MD5 to Historic

### ISSUE THREAD

**Issue by Neustradamus** [justingit/dada-mail#868] opened 2019-11-13 00:13 UTC
July 2011: RFC6331: Moving DIGEST-MD5 to Historic:
- https://tools.ietf.org/html/rfc6331

There are now:
- July 2010: RFC5802: Salted Challenge Response Authentication Mechanism (SCRAM): SASL and GSS-API Mechanisms: https://tools.ietf.org/html/rfc5802 (SCRAM-SHA-1 and SCRAM-SHA-1-PLUS)
- July 2010: RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803
- November 2015: RFC7677: SCRAM-SHA-256 and SCRAM-SHA-256-PLUS: Simple Authentication and Security Layer (SASL) Mechanisms: https://tools.ietf.org/html/rfc7677

**Comment by justingit** [comment] 2019-11-13 18:05
Stop spamming my issue tracker, please. If there is some specific bug you would like to report, please report it. One more time you open up a bug without an explanation of exactly the issue, you're being banned.

**Comment by Neustradamus** [comment] 2019-11-13 19:28
@justingit: It is two differents bugs.

One for implementation of SCRAM-SHA-X(-PLUS) and a second to remove old unsecured MD5 password.

**Comment by justingit** [comment] 2019-11-13 19:33
OK, what passwords in the app are being stored with  MD5 encryption?

**Comment by justingit** [comment] 2019-11-18 18:16
Closing, duplicate of, #867

**Closed by justingit** 2019-11-18 18:16 UTC
